# Title
site_name: Fiori Tracker Business
site_url: https://swaggin.github.io/mkdocs-template/

# Navigation
nav:
  - Introduction: 'index.md'
  - 'Fiori Tracker Business': 
      - Catalog Import: 'pages/ci/FPS01/index.md'
  - Installation: 'pages/inst.md'
  - FAQ: 'pages/faq.md'

# Plugins
plugins:
  - macros
  - search

# Theme
theme:
  name: 'material'
  logo: 'assets/images/FT-logo.png'
  favicon: 'assets/images/favicon.ico'

markdown_extensions:
  - def_list

# Variables
extra:
  example:
    title: 'Fiori Tracker Business'
  
